defaults:
  cluster_name: production-cluster
  env: production
  kubeconfig_path: "~/.kube/config"

namespaces:
  - ingress-nginx
  - cert-manager
  - vault
  - open-webui
  - postgresql
  - n8n
  - monitoring
  - argocd
  - redis

ingress_nginx:
  enabled: true
  name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx
  version: 4.14.3
  repository: https://kubernetes.github.io/ingress-nginx
  values:
    enabled: true
    controller:
      kind: Deployment
      replicaCount: 3
      service:
        type: LoadBalancer
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
      ingressClassResource:
        name: nginx
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 80

cert_manager:
  enabled: true
  name: cert-manager
  namespace: cert-manager
  chart: cert-manager
  version: v1.17.1
  repository: https://charts.jetstack.io
  values:
    crds:
      enabled: true
    replicaCount: 2
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: ClusterIssuer
    extraArgs:
      - --enable-certificate-owner-ref=true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

postgresql:
  enabled: true
  name: postgresql
  namespace: postgresql
  chart: postgresql
  version: 16.6.7
  repository: oci://registry-1.docker.io/bitnamicharts
  values:
    primary:
      persistence:
        enabled: true
        size: 50Gi
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    readReplicas:
      replicaCount: 2
      persistence:
        enabled: true
        size: 50Gi
    metrics:
      enabled: true
    volumePermissions:
      enabled: true
    backup:
      enabled: true

vault:
  enabled: true
  name: vault
  namespace: vault
  chart: vault
  version: 0.30.0
  repository: https://helm.releases.hashicorp.com
  values:
    global:
      enabled: true
    injector:
      enabled: true
      replicas: 2
    ui:
      enabled: true
    server:
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: vault.example.com
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.example.com
      dataStorage:
        enabled: true
        size: 50Gi
        accessMode: ReadWriteOnce
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi

open_webui:
  enabled: true
  name: open-webui
  namespace: open-webui
  chart: open-webui
  version: 6.11.0
  repository: https://helm.openwebui.com
  values:
    ollama:
      enabled: false
    pipelines:
      enabled: false
    ingress:
      enabled: true
      class: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: "chat.example.com"
      tls:
        - hosts:
            - "chat.example.com"
          secretName: "open-webui-tls"
    resources:
      limits:
        cpu: 2000m
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    persistence:
      enabled: true
      size: 50Gi

n8n:
  enabled: true
  name: n8n
  namespace: n8n
  chart: n8n
  version: 1.5.10
  repository: https://community-charts.github.io/helm-charts
  values:
    main:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
    db:
      type: postgresdb
    externalPostgresql:
      host: "postgresql.postgresql.svc.cluster.local"
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - n8n.example.com
          secretName: n8n-tls

monitoring:
  enabled: true
  name: kube-prometheus-stack
  namespace: monitoring
  chart: kube-prometheus-stack
  version: 82.2.0
  repository: https://prometheus-community.github.io/helm-charts
  values:
    prometheus:
      prometheusSpec:
        retention: 30d
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 200Gi
    grafana:
      enabled: true
      replicas: 2
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.example.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.example.com
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    alertmanager:
      enabled: true
      alertmanagerSpec:
        replicas: 2
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true

argocd:
  enabled: true
  name: argocd
  namespace: argocd
  chart: argo-cd
  version: 9.4.3
  repository: https://argoproj.github.io/argo-helm
  values:
    global:
      domain: argocd.example.com
    server:
      replicas: 2
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls: true
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
    repoServer:
      replicas: 2
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    configs:
      params:
        server.insecure: false

redis:
  enabled: true
  name: redis
  namespace: redis
  chart: redis
  version: 20.11.3
  repository: oci://registry-1.docker.io/bitnamicharts
  values:
    architecture: replication
    auth:
      enabled: true
    master:
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    replica:
      replicaCount: 2
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    metrics:
      enabled: true
