defaults:
  cluster_name: staging-cluster
  kube_context: staging-cluster
  env: staging
  kubeconfig_path: "~/.kube/config"

namespaces:
  - ingress-nginx
  - cert-manager
  - vault
  - open-webui
  - postgresql
  - n8n
  - monitoring
  - redis

ingress_nginx:
  enabled: true
  name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx
  version: 4.14.3
  repository: https://kubernetes.github.io/ingress-nginx
  values:
    enabled: true
    controller:
      kind: Deployment
      replicaCount: 2
      service:
        type: LoadBalancer
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
      ingressClassResource:
        name: nginx
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

cert_manager:
  enabled: true
  name: cert-manager
  namespace: cert-manager
  chart: cert-manager
  version: v1.17.1
  repository: https://charts.jetstack.io
  values:
    crds:
      enabled: true
    ingressShim:
      defaultIssuerName: selfsigned-issuer
      defaultIssuerKind: ClusterIssuer
    extraArgs:
      - --enable-certificate-owner-ref=true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

postgresql:
  enabled: true
  name: postgresql
  namespace: postgresql
  chart: postgresql
  version: 16.6.7
  repository: oci://registry-1.docker.io/bitnamicharts
  values:
    primary:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
    readReplicas:
      replicaCount: 1
      persistence:
        enabled: true
        size: 10Gi
    volumePermissions:
      enabled: true

vault:
  enabled: true
  name: vault
  namespace: vault
  chart: vault
  version: 0.30.0
  repository: https://helm.releases.hashicorp.com
  auto_init:
    enabled: true
    key_shares: 3
    key_threshold: 2
  values:
    global:
      enabled: true
    injector:
      enabled: true
    ui:
      enabled: true
    server:
      standalone:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-issuer
        hosts:
          - host: vault.staging.example.com
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.staging.example.com
      dataStorage:
        enabled: true
        size: 10Gi
        accessMode: ReadWriteOnce

open_webui:
  enabled: true
  name: open-webui
  namespace: open-webui
  chart: open-webui
  version: 6.11.0
  repository: https://helm.openwebui.com
  values:
    ollama:
      enabled: false
    pipelines:
      enabled: false
    ingress:
      enabled: true
      class: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
      host: "chat.staging.example.com"
      tls:
        - hosts:
            - "chat.staging.example.com"
          secretName: "open-webui-tls"
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      size: 10Gi

n8n:
  enabled: true
  name: n8n
  namespace: n8n
  chart: n8n
  version: 1.5.10
  repository: https://community-charts.github.io/helm-charts
  values:
    main:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    db:
      type: postgresdb
    externalPostgresql:
      host: "postgresql.postgresql.svc.cluster.local"
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: n8n.staging.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - n8n.staging.example.com
          secretName: n8n-tls

monitoring:
  enabled: true
  name: kube-prometheus-stack
  namespace: monitoring
  chart: kube-prometheus-stack
  version: 82.2.0
  repository: https://prometheus-community.github.io/helm-charts
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: selfsigned-issuer
        hosts:
          - grafana.staging.example.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.staging.example.com
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    alertmanager:
      enabled: true
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true

redis:
  enabled: true
  name: redis
  namespace: redis
  chart: redis
  version: 20.11.3
  repository: oci://registry-1.docker.io/bitnamicharts
  values:
    architecture: standalone
    auth:
      enabled: true
    master:
      persistence:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
